### ISSUE TITLE
Argument 1 passed to Jade\Node::addChild() must be an instance of Jade\Node

### ISSUE THREAD

**Issue by cyrusdavid** [opendena/jade.php#2]
``` php
$parser = new \Jade\Parser(new \Jade\Lexer());
$dumper = new \Jade\Dumper();
$jade = new \Jade\Jade($parser, $dumper);

$html = <<<EOF
!!! 5
  html
EOF;
exit(var_dump(($jade->render($html)));
```

**Comment by cyrusdavid** [comment]
``` php
$html ="!!! 5
  html
    title Hello World";
exit(var_dump(($jade->render($html)));
```

The same happens.

**Comment by SebastienElet** [comment]
Hello,

Thanks for your report, i did several tests and this is not a bug.
Jade does not expect any indent after the doctype declaration.

Your template is also invalid with native jade.

The fallowing code works

``` php
$parser = new \Jade\Parser(new \Jade\Lexer());
$dumper = new \Jade\Dumper();
$jade = new \Jade\Jade($parser, $dumper);

$html = <<<EOF
!!! 5
html
EOF;
exit(var_dump($jade->render($html)));
```

I admit the error message should be smarter (like the js one)

```
Error: test.jade:2
    1| !!! 5
  > 2|   html
    3|     title Hello
    4|

unexpected token "indent"
```

**Comment by cyrusdavid** [comment]
Oh, haha. Sorry about that.

**Comment by SebastienElet** [comment]
No problem, your issue pointed a serious lack of information for such error.

**Comment by cyrusdavid** [comment]
btw, can I pass an option/argument somewhere to enable/disable pretty-print?

**Comment by SebastienElet** [comment]
Could you open another issue with some examples of what you want to do please ?
